Add Tables, Loops and ArrayFactory
awwkoala/learning pull request #1
Opened 2021-07-08 09:31 UTC by awwkoala

2021-07-08 10:59 UTC, lgonczarik commented on .gitignore
> +target
It is good practice to have the file ends with an empty line (for later easier merge and other resons).

2021-07-08 10:59 UTC, lgonczarik commented on pom.xml
> +</project>
Same here, keep an empty line at the end of the file.

2021-07-08 10:59 UTC, lgonczarik commented on src/main/java/ArrayFactory.java
> +    private int x;
Not an issue but for future reference.
We use tabs size equal 2 spaces, so I advise to change this in your IJ ;)

2021-07-08 10:59 UTC, lgonczarik commented on src/main/java/ArrayFactory.java
> +        return oneDim;
Keep Your code as simple as possible.
You don't need here additional variable, just a return an array.

2021-07-08 10:59 UTC, lgonczarik commented on src/main/java/ArrayFactory.java
> +        return twoDim;
Same here just a simple return should be enough.

2021-07-08 10:59 UTC, lgonczarik commented on src/main/java/ArrayFactory.java
> +                    matrix[i][j] = 0;
KISS, by default in primitive value, is 0, so You don't need this else.

2021-07-08 10:59 UTC, lgonczarik commented on src/main/java/ArrayFactory.java
> +                if (i == j) {
In this case, You can use a single loop for this (equal arrays sizes, change only on the equal index).
so   matrix[i][i] = 1

2021-07-08 10:59 UTC, lgonczarik commented on src/main/java/Loops.java
> +    public void displayIntsUntil(int x) {
I would rename it to print..., word display is mainly used for UI components.
Word for writing text to terminal is `print`.

2021-07-08 10:59 UTC, lgonczarik commented on src/main/java/Loops.java
> +        int[] intList = new int[x + 1];
Remove this, use just loop.

2021-07-08 10:59 UTC, lgonczarik commented on src/main/java/Loops.java
> +        String[] separateInt = (a + "").split("");
String.valueOf(a) looks better instead (a + "").

2021-07-08 10:59 UTC, lgonczarik commented on src/main/java/Loops.java
> +        String[] separateInt = (a + "").split("");
Instead split You can use .toCharArray().

2021-07-08 10:59 UTC, lgonczarik commented on src/main/java/Loops.java
> +            wordTurned = wordTurned + word.charAt(i);
wordTurned += word.charAt(i);

2021-07-08 10:59 UTC, lgonczarik commented on src/main/java/Loops.java
> +        String wordTurned = "";
For future reference, You can use build-in functions like 
```
StringBuffer sbr = new StringBuffer(str);
sbr.reverse();
```
but I understand that point of this exercise was a self-made method.

2021-07-08 10:59 UTC, lgonczarik commented on src/main/java/Loops.java
> +    public String intToBinary(int a) {
Just for note, in future You can use Integer.toBinaryString() :)

2021-07-08 10:59 UTC, lgonczarik commented on src/main/java/Loops.java
> +            int remainder;
I don't see a point why declaration and assignment are in a separate lines.

2021-07-08 10:59 UTC, lgonczarik commented on src/main/java/Loops.java
> +        while (a > 0) {
while is on, just for exercise You can try to replace it with for loop ;)

2021-07-08 10:59 UTC, lgonczarik commented on src/main/java/Loops.java
> +        return binary;
Just return instead of assignment and return.

2021-07-08 10:59 UTC, lgonczarik commented on src/main/java/Loops.java
> +        for (int i = 0; i < wordChArr.length; i++) {
If you check start and end, You should iterate to wordChArr.length / 2 :)

2021-07-08 10:59 UTC, lgonczarik commented on src/main/java/Loops.java
> +                isPalindrome = false;
return false instead to end loop faster.

2021-07-08 10:59 UTC, lgonczarik commented on src/main/java/Loops.java
> +    public String displayInts(int[] intTable) {
I would use String.join in this case in the real use case.

2021-07-08 10:59 UTC, lgonczarik commented on src/main/java/Loops.java
> +                intsString = intsString.substring(0, intsString.length() - 2);
Instead of removing the ending, You can iterate to intTable.length -1 and handle the last element separately at the end of the loop

2021-07-08 10:59 UTC, lgonczarik commented on src/main/java/Loops.java
> +    public int[] sortIntTable(int[] intTable) {
If this is a method for a specific type I wouldn't use the method name variable type name.
(sortIntTable -> sortTable).
Also in java "tablica" == array ;)

2021-07-08 10:59 UTC, lgonczarik commented on src/main/java/Loops.java
> +    }
Format :) (separate closing bracket from the last method to closing bracket from class with new line).

2021-07-08 10:59 UTC, lgonczarik commented on src/main/java/Tables.java
> +public class Tables {
It is not class that implements Tables, its more like TablesUtils (or more likely ArrayUtils) ;)

2021-07-08 10:59 UTC, lgonczarik commented on src/main/java/Tables.java
> +    public String[] firstFiveLetters() {
This is more likely firstLetters(int a) instead of firstFiveLetters(), but I'm not sure if the point of this exercise is this simple, so Your answer may be correct.

2021-07-08 10:59 UTC, lgonczarik commented on src/main/java/Tables.java
> +        while (i <= 4) {
Replace this with for loop.

2021-07-08 10:59 UTC, lgonczarik commented on src/main/java/Tables.java
> +        char[] fiveChars = new char[6];
Why this instead of just saving as a string?

2021-07-08 10:59 UTC, lgonczarik commented on src/main/java/Tables.java
> +            fiveLetters[i] = String.valueOf(fiveChars[i]);
fiveLetters[i] = String.valueOf((char) ('a' + i));

2021-07-08 10:59 UTC, lgonczarik commented on src/main/java/Tables.java
> +    public int[] turnAroundThreeInts(int a, int b, int c) {
"pobierającą trójelementową tablicę liczb" is int[] a ;)

2021-07-08 10:59 UTC, lgonczarik commented on src/main/java/Tables.java
> +            threeIntsTurned[i] = threeInts[j];
Use threeInts.lenght - 1 - i  instead additional index j.

2021-07-08 10:59 UTC, lgonczarik commented on src/main/java/Tables.java
> +        while (i <= 2 && j >= 0) {
For loop.

2021-07-08 13:56 UTC, awwkoala commented on src/main/java/Loops.java
> +    public String intToBinary(int a) {
Didn't apply here, but will remember :)

2021-07-08 13:58 UTC, awwkoala commented on src/main/java/Tables.java
> +    public String[] firstFiveLetters() {
I am not sure either :(

2021-07-08 14:02 UTC, awwkoala commented on src/main/java/Loops.java
> +    public String displayInts(int[] intTable) {
It is an integer array, so I can't use that

2021-07-09 06:18 UTC, ilusi0npl commented on src/main/java/Basics/ArrayUtils.java
> +package Basics;
bad package name

2021-07-09 11:49 UTC, lgonczarik commented on pom.xml
> +
2 free spaces are redundant ;)

2021-07-09 11:49 UTC, lgonczarik commented on src/main/java/basic/Loops.java
> +    } else {
return ends method execution so You don't need `else` in this case.

2021-07-09 11:49 UTC, lgonczarik commented on src/main/java/basic/ArrayFactory.java
> +    } else {
I won't comment this everywhere, but change exception handling like this to if without else (just skip else block).

2021-07-09 11:49 UTC, lgonczarik commented on src/main/java/basic/ArrayFactory.java
> +      throw new RuntimeException("Array can't have less than zero dimensions.");
Try to use less general exceptions, I think in this case the good idea would be https://docs.oracle.com/javase/7/docs/api/java/lang/IllegalArgumentException.html

2021-07-09 11:49 UTC, lgonczarik commented on src/test/java/basic/LoopsTest.java
> +    StringBuffer expectedString = new StringBuffer("fedcba");
why use string buffer instead of actual string?

2021-07-12 06:12 UTC, ilusi0npl requested changes

2021-07-12 06:12 UTC, ilusi0npl commented on src/test/java/basic/ArrayFactoryTest.java
> +package basic;
wrong package and project structure

2021-07-12 06:20 UTC, lgonczarik commented on pom.xml
> +      <version>3.20.2</version>
As the project grows, it's a good idea to keep dependencies versions as properties.

2021-07-12 06:20 UTC, lgonczarik commented on src/test/java/basic/ArrayUtilsTest.java
> +    Assertions.assertThat(actualArr).describedAs("integers array of three both positive and negative " +
Split as
Assertions.assertThat(actualArr)
   .describedAs()
   .isEqualTo()

2021-07-12 06:20 UTC, lgonczarik commented on src/test/java/basic/LoopsTest.java
> +    Assertions.assertThat(actualResult).describedAs("every character of the integer " + d + "is printed " +
As above, split by method call isntead of string spliting.

2021-07-12 06:20 UTC, lgonczarik commented on src/test/java/basic/LoopsTest.java
> +    Assertions.assertThat(actualResult).describedAs("every character of the integer " + d + "is printed " +
String.format()

2021-07-12 07:34 UTC, lgonczarik approved these changes

2021-07-12 08:56 UTC, merged